In [1]:
import numpy as np

#### Task 1

### Counts

count function

October 5th, 2020: 
Write a Python function called counts that takes a list as input and returns a dictionary of unique items in the list as keys and the number of times each item appears as values.
Example:
So, the input ['A', 'A', 'B', 'C', 'A']
should have output {'A': 3, 'B': 1, 'C': 1} . Your code should not depend
on any module from the standard library1 or otherwise. 

You should research the task first and include a description with references of your algorithm in the
notebook.


In [2]:
from collections import Counter
c1=Counter(['c','b','a','b','c','a','b','a','a','a','a','a','a','a','a', 'dog', '1', 'one'])
print (dict(c1))

{'c': 2, 'b': 3, 'a': 10, 'dog': 1, '1': 1, 'one': 1}


In [3]:
from collections import Counter
l =Counter(['1','1','1','1'])

In [4]:
print(l)
print (dict(l))


Counter({'1': 4})
{'1': 4}


### Task 2 

numpy & count function

Rolling Dice
***

Function that simulates rolling dice

2 Parameters
 k = number of dice
 r = number of times to roll the dice n
 
 module from standard python library 
 
 random module
 
 maybe plot bar chart
 
 
 
 
November 2nd, 2020: 

Write a Python function called dicerolls that simulates rolling dice. 
Your function should take two parameters: the number of dice k and the number of times to roll the dice n. 
The function should simulate randomly rolling k dice n times, keeping track of each total face value. 
It should then return a dictionary with the number of times each possible total face value occurred. 
So, calling the function as diceroll(k=2, n=1000) should return a dictionary like:
{2:19,3:50,4:82,5:112,6:135,7:174,8:133,9:114,10:75,11:70,12:36}
You can use any module from the Python standard library you wish and you should
include a description with references of your algorithm in the notebook.


In [5]:
# diceroll = (k=2, n=1000)

In [6]:
# Fair roll of 1 dice evenly

d = Counter(range(1,7))
d

Counter({1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1})

In [7]:
d2 = Counter(range(1,7))
d2

Counter({1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1})

In [8]:
import numpy as np

#def dicerolls(k):
    #number = [1, 2, 3, 4, 5, 6]
    #rng = np.random.default_rng()
    #roll = rng.choice([1, 2, 3, 4 ,5, 6], k)
    #quantity = []
    #faceval = 0
    #for i in range(0, k):
        #faceval = faceval + roll[i]
    #quantity.append()

In [9]:
def counts(inputList, caseSensitivity=True):
    
    if caseSensitivity==False:
        for i in range(0, len(inputList)):
            if isinstance(inputList[i], str):
                inputList[i] = inputList[i].lower()    
    
    return dict((element, inputList.count(element)) for element in set(inputList))

In [10]:
def dicerolls(k, n):
    number = [1, 2, 3, 4, 5, 6]
    rng = np.random.default_rng()
    rolls = []
    for i in range(n):
        roll = sum(rng.choice(number, k))
        rolls.append(roll)    
    outcome = counts(rolls)
    print(outcome)

In [11]:
dicerolls(2, 100000)

{2: 2755, 3: 5525, 4: 8347, 5: 11139, 6: 13791, 7: 16658, 8: 14057, 9: 11134, 10: 8247, 11: 5524, 12: 2823}


### Task 3
November 16th, 2020: 
The numpy.random.binomial function can be used to simulate flipping a coin with a 50/50 chance of heads or tails. 
Interestingly, if a coin is flipped many times then the number of heads is well approximated by a
bell-shaped curve. For instance, if we flip a coin 100 times in a row the chance of
getting 50 heads is relatively high, the chances of getting 0 or 100 heads is relatively
low, and the chances of getting any other number of heads decreases as you move
away from 50 in either direction towards 0 or 100. 

Write some python code that
    -simulates flipping a coin 100 times. 
    -Then run this code 1,000 times, keeping track
of the number of heads in each of the 1,000 simulations. 

Select an appropriate plot to depict the resulting list of 1,000 numbers, showing that it roughly follows
a bell-shaped curve. You should explain your work in a Markdown cell above the code.

In [12]:
rng = np.random.default_rng()
n, p = 100, .5
s = rng.binomial(n,p, 1000)
s

array([52, 50, 48, 58, 56, 50, 48, 48, 49, 46, 48, 46, 58, 48, 48, 53, 49,
       52, 40, 50, 47, 48, 51, 47, 45, 50, 53, 53, 48, 46, 48, 56, 49, 48,
       44, 51, 46, 53, 55, 46, 54, 49, 53, 53, 60, 52, 55, 51, 50, 55, 56,
       47, 51, 45, 48, 40, 42, 49, 57, 46, 54, 48, 52, 41, 55, 55, 48, 56,
       54, 50, 47, 61, 44, 43, 62, 53, 51, 53, 64, 43, 59, 46, 49, 43, 44,
       44, 46, 53, 48, 54, 48, 50, 55, 51, 55, 51, 51, 53, 52, 56, 45, 42,
       55, 61, 42, 50, 42, 44, 49, 50, 56, 57, 55, 56, 57, 48, 47, 50, 64,
       43, 45, 48, 46, 49, 52, 48, 60, 46, 45, 54, 56, 42, 49, 56, 49, 44,
       47, 52, 49, 45, 46, 47, 53, 46, 55, 48, 45, 60, 63, 40, 44, 50, 38,
       58, 50, 57, 46, 46, 53, 56, 49, 49, 47, 48, 59, 52, 50, 45, 54, 58,
       48, 46, 55, 55, 61, 46, 50, 47, 46, 53, 39, 45, 42, 45, 48, 48, 61,
       48, 50, 55, 51, 53, 50, 51, 47, 44, 33, 50, 46, 43, 40, 53, 55, 56,
       55, 52, 52, 51, 44, 48, 51, 48, 52, 47, 51, 50, 46, 56, 53, 50, 45,
       36, 63, 47, 46, 49

In [130]:
import pandas as pd

### Task 4 
November 30th, 2020: 
Simpson’s paradox is a well-known statistical paradox where a trend evident in a number of groups reverses when the groups are combined into one big data set. 
Use numpy to create four data sets, each with an x array and a corresponding y array, to demonstrate Simpson’s paradox. 
You might create your x arrays using numpy.linspace and create the y array for each x using notation like y = a * x + b where you choose the a and b for each x , y pair to demonstrate the paradox. 
You might see the Wikipedia page for Simpson’s paradox for inspiration.

Simpsons Paradox Wikipedia page.
https://en.wikipedia.org/wiki/Simpson%27s_paradox#:~:text=Simpson's%20paradox%2C%20which%20also%20goes,when%20these%20groups%20are%20combined.



In [211]:
x = np.linspace(17.0, 119.0, num=4)
a = 2
b = 15
y = (a * x + b)
print(x)
print(y)

[ 17.  51.  85. 119.]
[ 49. 117. 185. 253.]


In [212]:
#a = 2
#b = 15
#y = (a * x + b)
#y

In [216]:
data = [['apples'], ['oranges'], ['bananas'] ,['pears']]
df = pd.DataFrame(data, columns = ['Fruit']) 
df.set_index('Fruit',inplace=True)
df['Arg_Total_Rec'] = x
df['Arg_rotten_amt'] = np.linspace(2.0, 8.0, num=4)
df['Aus_Total_Rec'] = y
df['Aus_rotten_amt'] = np.linspace(11.0, 113.0, num=4)
sum_total = df['Arg_Total_Rec'] + df['Aus_Total_Rec']
df['Total'] = (sum_total)
sum_rotten = df['Arg_rotten_amt'] + df['Aus_rotten_amt']
df['Total_rotten'] = (sum_rotten)
new_row = {'Arg_Total_Rec': 272, 'Arg_rotten_amt': 20,'Aus_Total_Rec':604, 'Aus_rotten_amt': 248, 'Total':876, 'Total_rotten':268}
df = df.append(pd.Series(new_row, index=df.columns, name='Total'))
df

Arg_Total_Rec  Arg_rotten_amt  Aus_Total_Rec  Aus_rotten_amt  Total  \
Fruit                                                                          
apples            17.0             2.0           49.0            11.0   66.0   
oranges           51.0             4.0          117.0            45.0  168.0   
bananas           85.0             6.0          185.0            79.0  270.0   
pears            119.0             8.0          253.0           113.0  372.0   
Total            272.0            20.0          604.0           248.0  876.0   

         Total_rotten  
Fruit                  
apples           13.0  
oranges          49.0  
bananas          85.0  
pears           121.0  
Total           268.0

In [174]:
#df['Argentina'] = np.linspace(2.0, 8.0, num=4)

#df['2020_Rating'] = np.random.poisson(df['Rating'], len(df))

df['Arg_Total_Rec'] = x

In [175]:
df['Arg_rotten_amt'] = np.linspace(2.0, 8.0, num=4)

In [176]:
# df['ARG_%'] = (%['Argentina'])
#https://www.geeksforgeeks.org/how-to-calculate-the-percentage-of-a-column-in-pandas/?ref=rp
#df['ARG_%'] = (df['Arg_rotten_amt'] / df['Arg_Total_Rec'].sum()) * 100
#https://stackoverflow.com/questions/36619631/how-to-divide-two-column-in-a-dataframe

#df['ARG_%'] = (df['Arg_rotten_amt'] / df['Arg_Total_Rec']) * 100

In [177]:
df['Aus_Total_Rec'] = y

In [178]:
df['Aus_rotten_amt'] = np.linspace(11.0, 113.0, num=4)

In [179]:
#https://www.geeksforgeeks.org/how-to-calculate-the-percentage-of-a-column-in-pandas/?ref=rp
#https://stackoverflow.com/questions/36619631/how-to-divide-two-column-in-a-dataframe
#df['OZ_%'] = (df['Aus_rotten_amt'] / df['Aus_Total_Rec']) * 100

In [180]:
sum_total = df['Arg_Total_Rec'] + df['Aus_Total_Rec']
df['Total'] = (sum_total)

In [181]:
sum_rotten = df['Arg_rotten_amt'] + df['Aus_rotten_amt']
df['Total_rotten'] = (sum_rotten)

In [182]:
#sum_per = df['ARG_%'] + df['OZ_%']
#df['Total_%'] = (sum_per)
#https://stackoverflow.com/questions/36619631/how-to-divide-two-column-in-a-dataframe
#df['Total_%'] = (df['Total_rotten'] / df['Total']) * 100

In [189]:
df

Arg_Total_Rec  Arg_rotten_amt  Aus_Total_Rec  Aus_rotten_amt  Total  \
Fruit                                                                          
apples            17.0             2.0           49.0            11.0   66.0   
oranges           51.0             4.0          117.0            45.0  168.0   
bananas           85.0             6.0          185.0            79.0  270.0   
pears            119.0             8.0          253.0           113.0  372.0   

         Total_rotten  
Fruit                  
apples           13.0  
oranges          49.0  
bananas          85.0  
pears           121.0

In [190]:
#Total = df['Arg_Total_Rec']

#df = df.append(new_row, ignore_index=False)
#https://pythonexamples.org/pandas-dataframe-add-append-row/

#new_row = {'Fruit':'Total'}
#df = df.append(new_row, ignore_index=True)
#df.loc['Total',:]= df.sum(axis=0)
#https://thispointer.com/pandas-sum-rows-in-dataframe-all-or-certain-rows/

#df.append(df.sum().rename('Total')).assign(Total=lambda d: d.sum(1))
                                                                  

In [206]:
new_row = {'Arg_Total_Rec': 272, 'Arg_rotten_amt': 20,'Aus_Total_Rec':604, 'Aus_rotten_amt': 248, 'Total':876, 'Total_rotten':268}
#df1 = df.append(new_row,ignore_index=True)
#df1 = df.append_index('Fruit',inplace=True)
df = df.append(pd.Series(new_row, index=df.columns, name='Total'))
df

Arg_Total_Rec  Arg_rotten_amt  Aus_Total_Rec  Aus_rotten_amt  Total  \
Fruit                                                                          
apples            17.0             2.0           49.0            11.0   66.0   
oranges           51.0             4.0          117.0            45.0  168.0   
bananas           85.0             6.0          185.0            79.0  270.0   
pears            119.0             8.0          253.0           113.0  372.0   
Total            272.0            20.0          604.0           248.0  876.0   

         Total_rotten  
Fruit                  
apples           13.0  
oranges          49.0  
bananas          85.0  
pears           121.0  
Total           268.0

In [199]:
df.sum(axis =0)

Arg_Total_Rec     272.0
Arg_rotten_amt     20.0
Aus_Total_Rec     604.0
Aus_rotten_amt    248.0
Total             876.0
Total_rotten      268.0
dtype: float64

In [209]:
df['ARG_%'] = (df['Arg_rotten_amt'] / df['Arg_Total_Rec']) * 100
df['OZ_%'] = (df['Aus_rotten_amt'] / df['Aus_Total_Rec']) * 100
df['Total_%'] = (df['Total_rotten'] / df['Total']) * 100
df

Arg_Total_Rec  Arg_rotten_amt  Aus_Total_Rec  Aus_rotten_amt  Total  \
Fruit                                                                          
apples            17.0             2.0           49.0            11.0   66.0   
oranges           51.0             4.0          117.0            45.0  168.0   
bananas           85.0             6.0          185.0            79.0  270.0   
pears            119.0             8.0          253.0           113.0  372.0   
Total            272.0            20.0          604.0           248.0  876.0   

         Total_rotten       OZ_%    Total_%      ARG_%  
Fruit                                                   
apples           13.0  22.448980  19.696970  11.764706  
oranges          49.0  38.461538  29.166667   7.843137  
bananas          85.0  42.702703  31.481481   7.058824  
pears           121.0  44.664032  32.526882   6.722689  
Total           268.0  41.059603  30.593607   7.352941